### ISSUE TITLE
Difficulty with Rexster Integration

### ISSUE THREAD

**Issue by Lab41PaulM** [v5analytics/vertexium#11]
In an effort to get Rester running with Vertexium, I have followed the README provided (making some modifications like providing the full classname), however have run into an issue that I can't seem to figure out.   Any guidance would be appreciated.

My rexster.xml
```    
<graph>
    <graph-name>org.vertexium.accumulo.AccumuloGraph</graph-name>
    <graph-type>org.vertexium.accumulo.blueprints.AccumuloVertexiumRexsterGraphConfiguration</graph-type>
    <storage>org.vertexium.accumulo.blueprints.AccumuloVertexiumBlueprintsGraphFactory</storage>
    <graph-useServerSideElementVisibilityRowFilter>false</graph-useServerSideElementVisibilityRowFilter>
    <graph-accumuloInstanceName>[INSTANCE_NAME]</graph-accumuloInstanceName>
    <graph-username>root</graph-username>
    <graph-password>[PASSWORD]</graph-password>
    <graph-tableNamePrefix>baseball</graph-tableNamePrefix>
    <graph-zookeeperServers>[IP_ADDRESS]</graph-zookeeperServers>
    <graph-serializer>org.vertexium.accumulo.serializer.JavaValueSerializer</graph-serializer>
    <graph-idgenerator>org.vertexium.id.UUIDIdGenerator</graph-idgenerator>
    <graph-search>org.vertexium.elasticsearch.ElasticSearchSearchIndex</graph-search>
    <graph-search-locations>[IP_ADDRESS]</graph-search-locations>
    <graph-search-indexName>baseball</graph-search-indexName>
    <visibilityProvider>org.vertexium.blueprints.DefaultVisibilityProvider</visibilityProvider>
   <authorizationsProvider>org.vertexium.accumulo.blueprints.AccumuloAuthorizationsProvider</authorizationsProvider>
    <authorizationsProvider-auths>1,2,3,A,B,C,HIGH_INTEREST,SENSITIVE,SOME_INTEREST,UNKNOWN_INTEREST</authorizationsProvider-auths>
    <extensions>
        <allows>
            <allow>tp:gremlin</allow>
        </allows>
    </extensions>
</graph>
```

...Just to show that I have the jar in my class path and the AccumuloAuthorizationsProvider class is there...
```
$ jar tf /usr/local/rexster/lib/vertexium-accumulo-blueprints-0.10.1-SNAPSHOT.jar 
META-INF/
META-INF/MANIFEST.MF
org/
org/vertexium/
org/vertexium/accumulo/
org/vertexium/accumulo/blueprints/
org/vertexium/accumulo/blueprints/AccumuloAuthorizationsProvider.class
org/vertexium/accumulo/blueprints/AccumuloVertexiumBlueprintsGraph.class
org/vertexium/accumulo/blueprints/AccumuloVertexiumBlueprintsGraphFactory.class
org/vertexium/accumulo/blueprints/AccumuloVertexiumRexsterGraphConfiguration.class
META-INF/maven/
META-INF/maven/org.vertexium/
META-INF/maven/org.vertexium/vertexium-accumulo-blueprints/
META-INF/maven/org.vertexium/vertexium-accumulo-blueprints/pom.xml
META-INF/maven/org.vertexium/vertexium-accumulo-blueprints/pom.properties
```
The Exception after running  ./bin/rexster.sh --start....
Caused by: java.lang.NullPointerException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at org.vertexium.util.ConfigurationUtils.createProvider(ConfigurationUtils.java:24)
        ... 10 more
[WARN] GraphConfigurationContainer - Could not create authorization provider
org.vertexium.VertexiumException: Could not create authorization provider
        at org.vertexium.accumulo.blueprints.AccumuloVertexiumBlueprintsGraphFactory.createAuthorizationsProvider(AccumuloVertexiumBlueprintsGraphFactory.java:42)
        at org.vertexium.accumulo.blueprints.AccumuloVertexiumBlueprintsGraphFactory.createGraph(AccumuloVertexiumBlueprintsGraphFactory.java:17)
        at org.vertexium.accumulo.blueprints.AccumuloVertexiumRexsterGraphConfiguration.configureGraphInstance(AccumuloVertexiumRexsterGraphConfiguration.java:30)
        at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:119)
        at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
        at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
        at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
        at com.tinkerpop.rexster.Application.<init>(Application.java:96)
        at com.tinkerpop.rexster.Application.main(Application.java:188)
Caused by: org.vertexium.VertexiumException: java.lang.NullPointerException
        at org.vertexium.util.ConfigurationUtils.createProvider(ConfigurationUtils.java:52)
        at org.vertexium.util.ConfigurationUtils.createProvider(ConfigurationUtils.java:16)
        at org.vertexium.accumulo.blueprints.AccumuloVertexiumBlueprintsGraphFactory.createAuthorizationsProvider(AccumuloVertexiumBlueprintsGraphFactory.java:40)
        ... 8 more
Caused by: java.lang.NullPointerException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at org.vertexium.util.ConfigurationUtils.createProvider(ConfigurationUtils.java:24)
        ... 10 more

**Comment by joeferner** [comment]
Sorry, I haven't updated that documentation in a long time. I just made some changes to the documentation that hopefully clears up your problem. Mainly `visibilityProvider`, `authorizationsProvider`, and `authorizationsProvider-auths` should be prefixed with `graph-`

**Comment by Lab41PaulM** [comment]
Up and running with Rexster!  Thanks.
